services:
  - type: web
    name: w-music
    runtime: python
    buildCommand: "cd frontend && npm install && npm run build && pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -k uvicorn.workers.UvicornWorker backend.main:app"
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/mateodevcode/w-music
    buildFilter:
      paths:
        - backend/**
        - frontend/**
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
