services:
  - type: web
    name: w-music
    runtime: python
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 10000"
    region: oregon
    plan: free
    branch: main
    repo: https://github.com/mateodevcode/w-music
    buildFilter:
      paths:
        - backend/**
        - frontend/**
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.2"
